orbs:
  node: circleci/node@5.1.0
version: 2.1

# Basic workflow: Checkout, build, then deploy if npm version was changed

jobs:
  publish:
    docker:
      - image: node:lts
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Build CSS
          command: npm run css
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  tagged-build:
    jobs:
      - publish:
          filters:
            branches:
              only: main
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
