name: CSS

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NODE: 18

permissions:
  contents: write

jobs:
  css:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run CSS
        run: npm run css

      - name: Commit and push changes to dist
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@example.com"
          git add dist/*
          git commit -m "Update dist directory after CSS build" || echo "No changes to commit"
          git push
